$AppName = "ADUpdate"
$RepoName = "it-powershell-adupdate"
$SourceDir = "C:\ProgramData\chocolatey\lib\$RepoName"
$DestinationDir = "C:\Test\$AppName"
#$DestinationDir = "C:\Windows\SYSVOL\domain\scripts\$AppName"